# Generated by Django 4.2.3 on 2023-08-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prod', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description_prod', models.CharField(max_length=100, verbose_name='Описание')),
                ('img_prod', models.ImageField(blank=True, null=True, upload_to='preview', verbose_name='Превью')),
                ('category_prod', models.CharField(max_length=100, verbose_name='Категория')),
                ('price_prod', models.IntegerField(blank=True, help_text='Введите цену продукта в рублях', null=True, verbose_name='Цена')),
                ('data_create_prod', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('data_change_prod', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
